version: '{branch}-{build}'

environment:
  matrix:
    - PYTHON: "C:\\Python27"
      TOX_ENV: py27
    - PYTHON: "C:\\Python35"
      TOX_ENV: py35
    - PYTHON: "C:\\Python36"
      TOX_ENV: py36

build: false

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - pip install tox

test_script:
  - "tox -e %TOX_ENV%"
