import os
import sys
import shutil
import random

from scrapy.utils.conf import closest_scrapy_cfg
from scrapy.commands.genspider import sanitize_module_name


TEST_TEMPLATE = """# THIS IS A GENERATED FILE
# Generated by: {command}  # noqa: E501
import os
import unittest
from scrapy_autounit.player import Player


class AutoUnit(unittest.TestCase):
    def test__{test_name}(self):
        _dir = os.path.dirname(os.path.abspath(__file__))
        player = Player(_dir)
        player.test()

if __name__ == '__main__':
    unittest.main()
"""


class Recorder:
    def __init__(self, crawler, *args, **kwargs):
        self.settings = crawler.settings
        self.spider_name = sanitize_module_name(crawler.spider.name)

        self.base_path = self.settings.get(
            'AUTOUNIT_BASE_PATH',
            default=os.path.join(self._get_project_dir(), 'autounit')
        )

        self.fixture_counters = {}
        self._set_max_fixtures()

        self._create_dir(self.base_path, exist_ok=True)
        self._clear_fixtures()

    def _set_max_fixtures(self):
        self.max_fixtures = self.settings.getint(
            'AUTOUNIT_MAX_FIXTURES_PER_CALLBACK',
            default=10
        )
        if self.max_fixtures < 10:
            self.max_fixtures = 10

    def _get_project_dir(self):
        closest_cfg = closest_scrapy_cfg()
        if closest_cfg:
            return os.path.dirname(closest_cfg)

    def _get_test_dir(self, callback_name):
        components = [self.base_path, 'tests', self.spider_name]
        extra = self.settings.get('AUTOUNIT_EXTRA_PATH')
        if extra:
            components.append(extra)
        components.append(callback_name)
        test_dir = None
        for comp in components:
            test_dir = os.path.join(test_dir, comp) if test_dir else comp
            self._create_dir(test_dir, parents=True, exist_ok=True)
            init_file = os.path.join(test_dir, '__init__.py')
            with open(init_file, 'a'):
                os.utime(init_file, None)
        test_name = '__'.join(components[2:])
        return test_dir, test_name

    def _create_dir(self, path, parents=False, exist_ok=False):
        try:
            if parents:
                os.makedirs(path)
            else:
                os.mkdir(path)
        except OSError:
            if not exist_ok:
                raise

    def _clear_fixtures(self):
        path = os.path.join(self.base_path, 'tests', self.spider_name)
        shutil.rmtree(path, ignore_errors=True)

    def _add_sample(self, index, test_dir, cassette):
        filename = 'fixture%s.bin' % str(index)
        path = os.path.join(test_dir, filename)
        with open(path, 'wb') as outfile:
            outfile.write(cassette.pack())

    def _write_test(self, path, test_name):
        command = 'scrapy {}'.format(' '.join(sys.argv))
        test_path = os.path.join(path, 'test_fixtures.py')
        test_code = TEST_TEMPLATE.format(test_name=test_name, command=command)
        with open(str(test_path), 'w') as f:
            f.write(test_code)

    def record(self, cassette):
        callback_name = cassette.request['callback']
        callback_counter = self.fixture_counters.setdefault(callback_name, 0)
        self.fixture_counters[callback_name] += 1

        test_dir, test_name = self._get_test_dir(callback_name)

        index = 0
        if callback_counter < self.max_fixtures:
            index = callback_counter + 1
            self._add_sample(index, test_dir, cassette)
        else:
            r = random.randint(0, callback_counter)
            if r < self.max_fixtures:
                index = r + 1
                self._add_sample(index, test_dir, cassette)

        if index == 1:
            self._write_test(test_dir, test_name)
